submodels:
  - semanticID: "https://www.hsu-hh.de/aut/aas/identification"
    queryTemplates:
      - path: "../../e2e/application/configs/sm_identification/identity.tpl.sql"
        dbName: "submodel1"
    responseTemplatePath: "../../e2e/application/configs/sm_identification/response.tpl.json"
  - semanticID: "https://www.hsu-hh.de/aut/aas/nameplate"
    queryTemplates:
      - path: "../../e2e/application/configs/sm_nameplate/nameplate.tpl.sql"
        dbName: "submodel2"
    responseTemplatePath: "../../e2e/application/configs/sm_nameplate/response.tpl.json"
databases:
  - name: submodel1
    dbType: postgres
    dbConfig:
      host: "localhost"
      port: 5433
      user: "postgres"
      password: "password"
      database: "submodel1"
      sslmode: "disable"
  - name: submodel2
    dbType: postgres
    dbConfig:
      host: "localhost"
      port: 5434
      user: "postgres"
      password: "password"
      database: "submodel2"
      sslmode: "disable"
