release:
 - base-branch: 'main'
 
go:
- any:
  - changed-files:
    - any-glob-to-any-file: '*.go'

workflow:
- any:
  - changed-files:
    - any-glob-to-any-file: '.github/**/**'

test:
- any:
  - changed-files:
    - any-glob-to-any-file: 'e2e/**'
    - any-glob-to-any-file: 'test/**'

pages:
- any:
  - changed-files:
    - any-glob-to-any-file: '_config.yaml'

docs:
- any:
  - changed-files:
    - any-glob-to-any-file: 'assets/**'
    - any-glob-to-any-file: '*.md'
