
version: "3.4"

services:
  app:
    image: hiroyoshii/go-aas-proxy:develop
    volumes:
      - ${PWD}/e2e/application/configs:/app/configs
    environment:
      HTTP_PORT: ":8081"
      AAS_DB_HOST: postgres_aas
      AAS_DB_PORT: 5432
      AAS_DB_USER: mebee
      AAS_DB_PASSWORD: password
      AAS_DB_DATABASE: aas
      SUBMODEL_CONFIG_PATH: /app/configs/submodel_config.yaml
    ports:
      - 8081:8081
  postgres_aas:
    image: postgres:latest
    volumes:
      - ${PWD}/scripts/aas_schema.sql:/app/aas_schema.sql
      - ${PWD}/e2e/application/sql/aas:/app/sql
    restart: always
    environment:
      POSTGRES_USER: mebee
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: aas
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    options: >-
      --health-cmd "CMD pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

  postgres_submodel1:
    image: postgres:latest
    volumes:
      - ${PWD}/e2e/application/sql/submodel1:/app/sql
    restart: always
    environment:
      POSTGRES_USER: mebee
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: submodel1
      TZ: "Asia/Tokyo"
    ports:
      - 5433:5432
    options: >-
      --health-cmd "CMD pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

  postgres_submodel2:
    image: postgres:latest
    volumes:
      - ${PWD}/e2e/application/sql/submodel2:/app/sql
    restart: always
    environment:
      POSTGRES_USER: mebee
      POSTGRES_PASSWORD: password
      PGPASSWORD: password123
      POSTGRES_DB: submodel2
      TZ: "Asia/Tokyo"
    ports:
      - 5434:5432
    options: >-
      --health-cmd "CMD pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
