submodels:
  semanticID1:
      queryFie: <path> 
      dbConfig:
         endpoint: <endpoint>
  semanticID2:
      queryFie: <path> 
      dbConfig:
         endpoint: <endpoint>
conceptDescriptions:
   semanticID1:
      submodel: <id>
      field: <name>
      cdJson: <attributes>