name: Basyx API Integration

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Gen protobuf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17"
      - name: retrieve api spec from swaggerhub
        run: |
          mkdir -p ./generated/source/
          BASYX_SWAGGER=https://api.swaggerhub.com/apis/BaSyx/basyx_asset_administration_shell_http_rest_api/v1/swagger.yaml?resolved=true
          curl $BASYX_SWAGGER > ./generated/source/basyx-openapi.yaml
          go install -v github.com/google/gnostic@latest
          go install -v github.com/googleapis/gnostic-grpc@v0.1.0
          gnostic --grpc-out=./generated/proto basyx-openapi.yaml
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "latest"
      - name: generate go code
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2  
          buf generate
      - name: commit & push
        run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update"
            git push
          fi
