name: e2e testing
on: [push]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.17"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run scenario test
        run: |
          go install github.com/zoncoen/scenarigo/cmd/scenarigo@v0.14.2
          ./e2e/scenario_setup.sh
          scenarigo run -c e2e/scenario/scenariogo.yaml
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: e2e/k6-load/local_test.js
          flags: --vus 50 --duration 10s