name: e2e testing
on:
  push:
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  e2e-test:
    name: Run scenarigo and k6 test
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ">=1.17"
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Run scenario test
        run: |
          go install github.com/zoncoen/scenarigo/cmd/scenarigo@v0.14.2
          ./e2e/scenario_setup.sh
          curl http://localhost:8081/shells/smart.festo.com%2Fdemo%2Faas%2F1%2F1%2F454576463545648365874
          docker-compose -f e2e/docker-compose.yaml logs
          scenarigo run -c e2e/scenario/scenariogo.yaml
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.45.1/k6-v0.45.1-linux-amd64.tar.gz -L | tar xvz --strip-components 1  
      - name: Run load test
        run: |
          mkdir -p output
          ./k6 run e2e/k6-load/local_test.js
      - name: Archive load test results
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: load-test-report
          path: output/*