name: build

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Build
        run: go build -v ./...
      - name: Checkout And Build
        run: docker compose up -d postgres
      - name: Test
        run: go test -v ./...

