name: build

on: [pull_request]

permissions:
  contents: read

jobs:
  build:

    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        id: setup-go
        with:
          go-version-file: "go.mod"
      - name: Build
        run: go build -v ./...
      - name: Checkout And Build
        run: docker compose up -d postgres
      - name: Test
        run: go test -v ./...
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@7088d18dcb87884bc7b5a4000d5517d758e9aa13 # master
        with:
          image-ref: ''
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
        with:
          sarif_file: 'trivy-results.sarif'
