name: integration testing
on: [workflow_dispatch]
jobs:
  build:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run scenario test
        run: ./e2e/scenario_test.sh
      - name: Run k6 local test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: e2e/k6-load/local_test.js
          flags: --vus 50 --duration 10s