name: longrun testing
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  k6-test:
    name: Run scenarigo and k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up
        run: ./e2e/scenario_setup.sh
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.45.1/k6-v0.45.1-linux-amd64.tar.gz -L | tar xvz --strip-components 1  
      - name: Run load test
        run: |
          mkdir -p output
          ./k6 run e2e/k6-load/local_long_test.js
      - name: Archive load test results
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: load-test-report
          path: output/*