name: longrun testing
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  k6-test:
    name: Run scenarigo and k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up
        run: ./e2e/scenario_setup.sh
      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.45.1/k6-v0.45.1-linux-amd64.tar.gz -L | tar xvz --strip-components 1  
      - name: Run load test
        run: |
          mkdir -p output
          ./k6 run e2e/k6-load/local_long_test.js
      - name: Archive load test results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: load-test-report
          path: output/*